# Generated by Django 5.1.2 on 2024-11-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_drink_food_delete_book_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
