# Generated by Django 5.1.2 on 2024-11-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_food_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='amount',
            new_name='amount_available',
        ),
    ]
