# Generated by Django 5.1.2 on 2024-11-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_amount_food_amount_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='amount',
        ),
        migrations.AddField(
            model_name='drink',
            name='amount_available',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
