# Generated by Django 5.1.2 on 2024-11-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_drink_amount_drink_amount_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='amount_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='amount_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
